name: Build (Windows)

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  schedule:
    # Build once every fortnight
    - cron: "10 4 1,15 * *"

permissions:
  contents: write

jobs:
  build:
    name: "Build Windows Binary"
    strategy:
      matrix:
        win_ver: ["win32", "win64"]
        include:
          - vs_ver: "2022"
          - win_ver: win32
            vs_arch: "Win32"
          - win_ver: win64
            vs_arch: "x64"

    runs-on: "windows-${{ matrix.vs_ver }}"
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: "3"
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg-bc

    steps:
      - name: "⏳ Clone repo..."
        uses: actions/checkout@v3

      - name: "🖼️ Setup scene..."
        shell: bash
        run: mkdir -p build

      - name: "🔧 CMake: Configure"
        shell: bash
        working-directory: build
        run: |
          cmake \
            -D"CMAKE_BUILD_TYPE"="Release" \
            -A "${{ matrix.vs_arch }}" \
            ..
      - name: "🛠️ CMake: Build"
        working-directory: build
        run: cmake --build . --config Release

      - name: "📦 Packaging"
        shell: bash
        run: |
          DIST_SOURCE="dist/keyless-migu3d-${{ matrix.win_ver }}/"
          mkdir -p "${DIST_SOURCE}"

          cp -R build/Release/*.exe "${DIST_SOURCE}"
          cp LICENSE README.md "${DIST_SOURCE}"

      - name: "🚀 Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "keyless-migu3d-${{ matrix.win_ver }}"
          path: dist/

  release:
    needs: build
    runs-on: ubuntu-22.04
    name: "Release Windows Binary"
    strategy:
      matrix:
        win_ver: ["win32", "win64"]

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: "keyless-migu3d-${{ matrix.win_ver }}"
          path: dist/

      - name: "🗜️ Packaging"
        run: |
          set -ex

          cd dist/
          zip -r9 "../keyless-migu3d-${{ matrix.win_ver }}.zip" .

      - name: 📝 Draft Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "<to be filled>"
          draft: true
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: "*.zip"
